<?php
/** @var \Probance\M2connector\Block\Js\Cart $block */
$token = $block->getToken();

$addtocartButtonId = $block->getAddtocartButtonId();
$addtocartFormId = $block->getAddtocartFormId();
$productQuerySelector = $block->getProductQuerySelector();

?>
<script defer type="text/javascript" language="JavaScript">
    var Probance_Cartin = function(addedProductId, quoteId, customerEmail) {
        var typeID = 'email';
        var my_id = customerEmail;
        var pid = addedProductId;
        var aid = '';   // Simple product ID already passed in pid
        var bid = quoteId;
        var url = document.location.href;
        //===== PART 2. TAG CALL: DON'T MODIFY THIS PART =====

        var crm = null;
        try {
            crm = new PROBANCE_CRMTracker("<?= $token ?>", "Prob_Track", 90, "//t4.my-probance.one/webtrax", "idprob");
        } catch (err) {
            return;
        }
        if (crm == null) {
            return;
        }
        // To call Probance tracker
        var PROBANCE_tracker = new PROBANCE_trackers();
        PROBANCE_tracker.setCRM(crm);
        //To save your visitor identifier (declared in previous variables) if you've it
        if (my_id != null && my_id != undefined && my_id != '') {
            crm.setCustomer(my_id, typeID);
        }
        PROBANCE_tracker.doNotTrackOnInit();
        PROBANCE_tracker.init();
        // Tracking the add to cart
        if (pid == null || pid == undefined) {
            pid = '';
        }
        if (aid == null || aid == undefined) {
            aid = '';
        }
        if (bid == null || bid == undefined) {
            bid = '';
        }

        PROBANCE_tracker.trackEvent(url, [["product_id", pid], ["article_id", aid], ["basket_id", bid], ["action", "cart"]]);
        //=================================================================================================
    }
    
    let addToCartBtn = document.getElementById('<?= $addtocartButtonId ?>');
    if (addToCartBtn) addToCartBtn.addEventListener('click', function (e) {
        let addedProductForm = document.getElementById('<?= $addtocartFormId ?>')
        if (addedProductForm) {
            let addedProductId = addedProductForm.querySelector('<?= $productQuerySelector ?>').value;
            let customerEmail = '';
            let quoteId = '';
            try {
                if (window.localStorage.getItem("mage-cache-storage")) {
                    let cacheStorage = JSON.parse(localStorage['mage-cache-storage']);
                    if ("customer" in cacheStorage) {
                        if ("email" in cacheStorage.customer) {
                            customerEmail = cacheStorage.customer.email;
                        }
                    }
                    if ("cart" in cacheStorage) {
                        if ("quoteId" in cacheStorage.cart) {
                            quoteId = cacheStorage.cart.quoteId;
                        }
                    }
                }
            } catch (e) {
                console.warn('Something wrong with mage-cache-storage : '+e);
            }
            Probance_Cartin(addedProductId, quoteId, customerEmail);
        }
    });

</script>
