<script src="<?= $block->getScriptUrl() ?>"></script>
<script type="text/javascript" language="JavaScript">
    var ViewedPage = function(data) {
        var typeID = 'email';
        var my_id = ('customerEmail' in data) ? data.customerEmail : '';
        var pid = ('productId' in data) ? data.productId : '';
        var aid = '';
        var url = document.location.href;
        var crm=null;
        try {
            crm = new PROBANCE_CRMTracker("<?= $block->getToken() ?>", "Prob_Track", 90, "//t4.my-probance.one/webtrax", "idprob");
        } catch (err) {
            return;
        }
        if (crm == null) {
            return;
        }
        var PROBANCE_tracker = new PROBANCE_trackers();
        PROBANCE_tracker.setCRM(crm);
        if (my_id != null && my_id != undefined && my_id != '') {
            crm.setCustomer(my_id, typeID);
        }
        PROBANCE_tracker.doNotTrackOnInit();
        PROBANCE_tracker.init();
        if (pid == null || pid == undefined) {
            pid = '';
        }
        if (aid == null || aid == undefined) {
            aid = '';
        }
        PROBANCE_tracker.track(url, [["product_id", pid], ["article_id", aid], ["action", "visit"]]);
    };
    async function getCustomerData() {
        try {
            let url = '<?= $block->getVisitDataUrl() ?>';
            let controller = new AbortController();
            // Timeout de 2s
            setTimeout(() => controller.abort(), 2000);
            const response = await fetch(url, {
                signal: controller.signal,
                method: "GET",
                headers: {
                    'Accept': 'application/json',
                    'X-Requested-With': 'XMLHttpRequest',
                },
                pragma: "no-cache", "cache-control": "no-cache", 
                cache: "no-cache"
            });
            let result = await response.json();
            if (result.status && result.status !== "success") {
                throw 'Bad status : '+response;
            }
            ViewedPage(result.data);
        } catch(err) {
            console.error(err);
        }
    }
    getCustomerData();
</script>
