<?php
/** @var \Probance\M2connector\Block\Js\Visit $block */
$trackerTimeout = $block->getWaitTrackerTimeout();
$productId = $block->getProductId();
?>
<script defer type="text/javascript" language="JavaScript">
    var Probance_ViewedPage = function(customerEmail) {
        var typeID = 'email';
        var my_id = customerEmail;
        var pid = '<?= $productId ?>';
        var aid = '';
        var url = document.location.href;
        var crm=null;
        try {
            crm = new PROBANCE_CRMTracker("<?= $block->getToken() ?>", "Prob_Track", 90, "//t4.my-probance.one/webtrax", "idprob");
        } catch (err) {
            return;
        }
        if (crm == null) {
            return;
        }
        var PROBANCE_tracker = new PROBANCE_trackers();
        PROBANCE_tracker.setCRM(crm);
        if (my_id != null && my_id != undefined && my_id != '') {
            crm.setCustomer(my_id, typeID);
        }
        PROBANCE_tracker.doNotTrackOnInit();
        PROBANCE_tracker.init();
        if (pid == null || pid == undefined) {
            pid = '';
        }
        if (aid == null || aid == undefined) {
            aid = '';
        }
        PROBANCE_tracker.track(url, [["product_id", pid], ["article_id", aid], ["action", "visit"]]);
    };
    let customerEmail = '';
    try {
        if (window.localStorage.getItem("mage-cache-storage")) {
            let cacheStorage = JSON.parse(localStorage['mage-cache-storage']);
            if ("customer" in cacheStorage) {
                if ("email" in cacheStorage.customer) {
                    customerEmail = cacheStorage.customer.email;
                }
            }
        }
    } catch (e) {
        console.warn('Something wrong with mage-cache-storage : '+e);
    }
    Probance_waitFor(() => window.hasOwnProperty('PROBANCE_CRMTracker'), <?= (int) $trackerTimeout ?>).then(
        result => {Probance_ViewedPage(customerEmail)},
        error => {console.warn('PROBANCE_tracker not loaded : '+error)}
    )
</script>
