<script async src="<?= $block->getScriptUrl() ?>"></script>
<script>
    /**
     * Function to wait for predicates.
     * @param {function() : Boolean} predicate - A function that returns a bool
     * @param {Number} [timeout] - Optional maximum waiting time in ms after rejected
     */
    function Probance_waitFor(predicate, timeout) {
        return new Promise((resolve, reject) => {
            const check = () => {
                if (!predicate()) return;
                clearInterval(interval);
                resolve();
            };
            const interval = setInterval(check, 100);
            check();

            if (!timeout) return;
            setTimeout(() => {
                clearInterval(interval);
                reject('Predicate timeout');
            }, timeout);
        });
    }
</script>
