<?php

namespace Walkwizus\Probance\Model\Config\Source\Attribute;

use Magento\Framework\Data\OptionSourceInterface;

class Coupon implements OptionSourceInterface
{
    /**
     * @var array
     */
    protected $additionnalAttributes = [
        [
            'label' => 'Empty Field',
            'value' => 'empty_field',
        ],
        [
            'label' => 'Rule ID',
            'value' => 'rule_id',
        ],
        [
            'label' => 'Code',
            'value' => 'code',
        ],
        [
            'label' => 'Usage Limit',
            'value' => 'usage_limit'
        ],
        [
            'label' => 'Usage per Customer',
            'value' => 'usage_per_customer'
        ],
        [
            'label' => 'Times used',
            'value' => 'times_used',
        ],
        [
            'label' => 'Expiration Date',
            'value' => 'expiration_date',
        ],
        [
            'label' => 'Is Primary',
            'value' => 'is_primary',
        ],
        [
            'label' => 'Creation Date',
            'value' => 'created_at',
        ],
        [
            'label' => 'Coupon Code Type',
            'value' => 'type',
        ],
        [
            'label' => 'Generated by dotmailer',
            'value' => 'generated_by_dotmailer',
        ],
        [
            'label' => 'Rule Name',
            'value' => 'rule.name',
        ],
        [
            'label' => 'Rule Description',
            'value' => 'rule.description',
        ],
        [
            'label' => 'Rule Label',
            'value' => 'rule.label',
        ],
        [
            'label' => 'Rule Start Date',
            'value' => 'rule.from_date',
        ],
        [
            'label' => 'Rule End Date',
            'value' => 'rule.to_date',
        ],
        [
            'label' => 'Rule Uses per Customer',
            'value' => 'rule.uses_per_customer',
        ],
        [
            'label' => 'Rule Is Active',
            'value' => 'rule.is_active',
        ],
        [
            'label' => 'Rule Discount Amount',
            'value' => 'rule.discount_amount',
        ],
        [
            'label' => 'Rule Discount Quantity',
            'value' => 'rule.discount_qty',
        ],
        [
            'label' => 'Rule Discount Step',
            'value' => 'rule.discount_step',
        ],
        [
            'label' => 'Rule Apply to Shipping',
            'value' => 'rule.apply_to_shipping',
        ],
        [
            'label' => 'Rule Times Used',
            'value' => 'rule.times_used',
        ],
        [
            'label' => 'Rule is RSS',
            'value' => 'rule.is_rss',
        ],
        [
            'label' => 'Rule Coupon Type',
            'value' => 'rule.coupon_type',
        ],
        [
            'label' => 'Rule Use Auto Generation',
            'value' => 'rule.use_auto_generation',
        ],
        [
            'label' => 'Rule Uses per Coupon',
            'value' => 'rule.uses_per_coupon',
        ],
        [
            'label' => 'Rule Customer Group',
            'value' => 'rule.customer_group_code',
        ],
    ];

    /**
     * @return array
     */
    public function toOptionArray()
    {
        /*
        usort($this->additionnalAttributes, function($a, $b) {
            return $a['label'] <=> $b['label'];
        });
        */
        return $this->additionnalAttributes;
    }
}
